name: Birthday Reminder

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1  # Use a version that supports Node.js 16


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12 # Specify the Python version you want to use

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install openpyxl requests

      - name: Run Python Script
        run: python auto.py
